// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "short_code", Type: field.TypeString, Unique: true, Size: 10, SchemaType: map[string]string{"postgres": "varchar(10)"}},
		{Name: "original_url", Type: field.TypeString, Size: 2147483647},
		{Name: "click_count", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "expired", Type: field.TypeBool, Default: false},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "link_original_url",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Type: "HASH",
				},
			},
			{
				Name:    "link_expires_at",
				Unique:  false,
				Columns: []*schema.Column{LinksColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "expires_at IS NOT NULL",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LinksTable,
	}
)

func init() {
}
