// Code generated by ent, DO NOT EDIT.

package link

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the link type in the database.
	Label = "link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldShortCode holds the string denoting the short_code field in the database.
	FieldShortCode = "short_code"
	// FieldOriginalURL holds the string denoting the original_url field in the database.
	FieldOriginalURL = "original_url"
	// FieldClickCount holds the string denoting the click_count field in the database.
	FieldClickCount = "click_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the link in the database.
	Table = "links"
)

// Columns holds all SQL columns for link fields.
var Columns = []string{
	FieldID,
	FieldShortCode,
	FieldOriginalURL,
	FieldClickCount,
	FieldCreatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	ShortCodeValidator func(string) error
	// OriginalURLValidator is a validator for the "original_url" field. It is called by the builders before save.
	OriginalURLValidator func(string) error
	// DefaultClickCount holds the default value on creation for the "click_count" field.
	DefaultClickCount int64
	// ClickCountValidator is a validator for the "click_count" field. It is called by the builders before save.
	ClickCountValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Link queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByShortCode orders the results by the short_code field.
func ByShortCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortCode, opts...).ToFunc()
}

// ByOriginalURL orders the results by the original_url field.
func ByOriginalURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalURL, opts...).ToFunc()
}

// ByClickCount orders the results by the click_count field.
func ByClickCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClickCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
