// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"url_shortener/ent/link"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
}

// SetShortCode sets the "short_code" field.
func (_c *LinkCreate) SetShortCode(v string) *LinkCreate {
	_c.mutation.SetShortCode(v)
	return _c
}

// SetOriginalURL sets the "original_url" field.
func (_c *LinkCreate) SetOriginalURL(v string) *LinkCreate {
	_c.mutation.SetOriginalURL(v)
	return _c
}

// SetClickCount sets the "click_count" field.
func (_c *LinkCreate) SetClickCount(v int64) *LinkCreate {
	_c.mutation.SetClickCount(v)
	return _c
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_c *LinkCreate) SetNillableClickCount(v *int64) *LinkCreate {
	if v != nil {
		_c.SetClickCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCreate) SetCreatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCreatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *LinkCreate) SetExpiresAt(v time.Time) *LinkCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableExpiresAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCreate) SetID(v int64) *LinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LinkMutation object of the builder.
func (_c *LinkCreate) Mutation() *LinkMutation {
	return _c.mutation
}

// Save creates the Link in the database.
func (_c *LinkCreate) Save(ctx context.Context) (*Link, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCreate) defaults() {
	if _, ok := _c.mutation.ClickCount(); !ok {
		v := link.DefaultClickCount
		_c.mutation.SetClickCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := link.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCreate) check() error {
	if _, ok := _c.mutation.ShortCode(); !ok {
		return &ValidationError{Name: "short_code", err: errors.New(`ent: missing required field "Link.short_code"`)}
	}
	if v, ok := _c.mutation.ShortCode(); ok {
		if err := link.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "Link.short_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalURL(); !ok {
		return &ValidationError{Name: "original_url", err: errors.New(`ent: missing required field "Link.original_url"`)}
	}
	if v, ok := _c.mutation.OriginalURL(); ok {
		if err := link.OriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "original_url", err: fmt.Errorf(`ent: validator failed for field "Link.original_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClickCount(); !ok {
		return &ValidationError{Name: "click_count", err: errors.New(`ent: missing required field "Link.click_count"`)}
	}
	if v, ok := _c.mutation.ClickCount(); ok {
		if err := link.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "Link.click_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Link.created_at"`)}
	}
	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ShortCode(); ok {
		_spec.SetField(link.FieldShortCode, field.TypeString, value)
		_node.ShortCode = value
	}
	if value, ok := _c.mutation.OriginalURL(); ok {
		_spec.SetField(link.FieldOriginalURL, field.TypeString, value)
		_node.OriginalURL = value
	}
	if value, ok := _c.mutation.ClickCount(); ok {
		_spec.SetField(link.FieldClickCount, field.TypeInt64, value)
		_node.ClickCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(link.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
}

// Save creates the Link entities in the database.
func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Link, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
