// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"url_shortener/ent/link"
	"url_shortener/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks    []Hook
	mutation *LinkMutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *LinkUpdate) SetClickCount(v int64) *LinkUpdate {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableClickCount(v *int64) *LinkUpdate {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *LinkUpdate) AddClickCount(v int64) *LinkUpdate {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LinkUpdate) SetExpiresAt(v time.Time) *LinkUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableExpiresAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *LinkUpdate) ClearExpiresAt() *LinkUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdate) Mutation() *LinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdate) check() error {
	if v, ok := _u.mutation.ClickCount(); ok {
		if err := link.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "Link.click_count": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(link.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(link.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(link.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(link.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkMutation
}

// SetClickCount sets the "click_count" field.
func (_u *LinkUpdateOne) SetClickCount(v int64) *LinkUpdateOne {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableClickCount(v *int64) *LinkUpdateOne {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *LinkUpdateOne) AddClickCount(v int64) *LinkUpdateOne {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *LinkUpdateOne) SetExpiresAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableExpiresAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *LinkUpdateOne) ClearExpiresAt() *LinkUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdateOne) Mutation() *LinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Link entity.
func (_u *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdateOne) check() error {
	if v, ok := _u.mutation.ClickCount(); ok {
		if err := link.ClickCountValidator(v); err != nil {
			return &ValidationError{Name: "click_count", err: fmt.Errorf(`ent: validator failed for field "Link.click_count": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(link.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(link.FieldClickCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(link.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(link.FieldExpiresAt, field.TypeTime)
	}
	_node = &Link{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
