// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"url_shortener/ent/link"
	"url_shortener/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescShortCode is the schema descriptor for short_code field.
	linkDescShortCode := linkFields[1].Descriptor()
	// link.ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	link.ShortCodeValidator = func() func(string) error {
		validators := linkDescShortCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(short_code string) error {
			for _, fn := range fns {
				if err := fn(short_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// linkDescOriginalURL is the schema descriptor for original_url field.
	linkDescOriginalURL := linkFields[2].Descriptor()
	// link.OriginalURLValidator is a validator for the "original_url" field. It is called by the builders before save.
	link.OriginalURLValidator = linkDescOriginalURL.Validators[0].(func(string) error)
	// linkDescClickCount is the schema descriptor for click_count field.
	linkDescClickCount := linkFields[3].Descriptor()
	// link.DefaultClickCount holds the default value on creation for the click_count field.
	link.DefaultClickCount = linkDescClickCount.Default.(int64)
	// link.ClickCountValidator is a validator for the "click_count" field. It is called by the builders before save.
	link.ClickCountValidator = linkDescClickCount.Validators[0].(func(int64) error)
	// linkDescCreatedAt is the schema descriptor for created_at field.
	linkDescCreatedAt := linkFields[4].Descriptor()
	// link.DefaultCreatedAt holds the default value on creation for the created_at field.
	link.DefaultCreatedAt = linkDescCreatedAt.Default.(func() time.Time)
	// linkDescExpired is the schema descriptor for expired field.
	linkDescExpired := linkFields[6].Descriptor()
	// link.DefaultExpired holds the default value on creation for the expired field.
	link.DefaultExpired = linkDescExpired.Default.(bool)
}
